script/guest: include no-fetch option allowing just guest machine execution
Signed-off-by: Leonardo Sandoval <leonardo.sandoval.gonzalez@linux.intel.com>

diff --git a/scripts/guest b/scripts/guest
--- a/scripts/guest
+++ b/scripts/guest
@@ -28,6 +28,7 @@
 SHAREDIR=''
 GUESTDIR=''
 POST=''
+NOFETCH=''
 
 function usage() {
     cat << EOF
@@ -38,23 +39,26 @@ where OPTIONS are
     -s <share dir> : Share directory between host and guest
     -g <guest dir> : Guest directory where machine will be located
     -p             : Post results to the patchwork instance
-
+    -n             : Do not fetch, just update repos and launch guest machine
 EOF
 >&2
 
     exit 1
 }
 
-while getopts ":s:g:ph" opt; do
+while getopts ":s:g:pnh" opt; do
     case $opt in
 	s)
-	    SHAREDIR=$(readlink -e $OPTARG)
+	    SHAREDIR=$OPTARG
 	    ;;
 	g)
-	    GUESTDIR=$(readlink -e $OPTARG)
+	    GUESTDIR=$OPTARG
 	    ;;
 	p)
 	    POST='x'
+	    ;;
+	n)
+	    NOFETCH='x'
 	    ;;
 	h)
 	    usage
@@ -89,18 +93,22 @@ function clean() {
     )
 }
 
+test -z "$SHAREDIR" && { echo "Provide the share directory folder created with create-share-folder script"; usage; }
+test -z "$GUESTDIR" && { echo "Provide the guest directory folder created with create-guest-machine script"; usage; }
+
+# make sure the poky build folder exists
+test ! -d "$SHAREDIR" && { echo "Provide the share directory folder created with create-share-folder script"; usage; }
+test ! -d "$GUESTDIR" && { echo "Provide the guest directory folder created with create-guest-machine script"; usage; }
+
+SHAREDIR=$(readlink -e $SHAREDIR)
+GUESTDIR=$(readlink -e $GUESTDIR)
+
 # Define repo location and names
 PW=$SHAREDIR/patchwork
 PT=$SHAREDIR/patchtest
 PTOE=$SHAREDIR/patchtest-oe
 OECORE=$SHAREDIR/openembedded-core
 BB=$OECORE/bitbake
-
-# make sure SHAREDIR folder is provided by user
-test -z "$SHAREDIR" && { echo "Provide a SHAREDIR folder"; usage; }
-
-# make sure the poky build folder exists
-test ! -d "$GUESTDIR/poky" && { echo "Please run create-guest-machine -g $GUESTDIR"; exit 1; }
 
 # Clone or pull share repos
 for repo in $PW $PT $PTOE $OECORE $BB; do
@@ -110,49 +118,56 @@ done
 # include scripts into PATH
 export PATH="$PW/git-pw/:$PT:$PT/scripts:$PATH"
 
-# Get latest mboxes from the PW instance
-fetch-mboxes -r $OECORE -m $SHAREDIR/tmp/mboxes
+if [ -z "$NOFETCH" ]; then
+    # Get latest mboxes from the PW instance
+    fetch-mboxes -r $OECORE -m $SHAREDIR/tmp/mboxes
 
-# if now new mboxes, just quit
-test ! -d $SHAREDIR/tmp/mboxes && { echo "Exiting"; exit 0; }
+    # if now new mboxes, just quit
+    test ! -d $SHAREDIR/tmp/mboxes && { echo "Exiting"; exit 0; }
 
-# Check if old mboxes are present and backup these and its results
-# TODO: we must thing on something smarter to store past results
-# The first approach was the use of a git repository and git notes
-# but in this case a branch needs to be created in every run
-# and then use the post-summary script to get data from it.
-# A simpler approach is just storing plain texts and it is
-# the scripting does at the moment.
-if [ -d $SHAREDIR/mboxes ]; then
+    # Check if old mboxes are present and backup these and its results
+    # TODO: we must thing on something smarter to store past results
+    # The first approach was the use of a git repository and git notes
+    # but in this case a branch needs to be created in every run
+    # and then use the post-summary script to get data from it.
+    # A simpler approach is just storing plain texts and it is
+    # the scripting does at the moment.
+    if [ -d $SHAREDIR/mboxes ]; then
 
-    # Unique folder to store previous mboxes/results
-    now="$(date --iso-8601=minutes)"
+        # Unique folder to store previous mboxes/results
+        now="$(date --iso-8601=minutes)"
 
-    # Define and create unique backup dir
-    backup="$SHAREDIR/backup/$now"
-    test ! -d $backup && mkdir -p $backup
+        # Define and create unique backup dir
+        backup="$SHAREDIR/backup/$now"
+        test ! -d $backup && mkdir -p $backup
 
-    # backup mboxes
-    mv $SHAREDIR/mboxes $backup/mboxes
+        # backup mboxes
+        mv $SHAREDIR/mboxes $backup/mboxes
 
-    # backup results (if exists)
-    test -d $SHAREDIR/results && mv $SHAREDIR/results $backup/results
+        # backup results (if exists)
+        test -d $SHAREDIR/results && mv $SHAREDIR/results $backup/results
+    fi
+
+    # Move latest mboxes
+    mv $SHAREDIR/tmp/mboxes $SHAREDIR/mboxes
 fi
-
-# Move latest mboxes
-mv $SHAREDIR/tmp/mboxes $SHAREDIR/mboxes
 
 # launch qemu. Machine is assumed to be in the default build folder (build)
 (
-    cd $GUERSTDIR/$poky
-    if . oe-init-build-env; then
-	runqemu qemux86-64 core-image-patchtest \
-		nographic kvm \
-		qemuparams="-snapshot \
-                            -fsdev local,id=test_dev,path=$SHAREDIR,security_model=mapped \
-                            -device virtio-9p-pci,fsdev=test_dev,mount_tag=test_mount"
+    if [ -d $GUESTDIR/poky ]; then
+	cd $GUESTDIR/poky
+    	if . oe-init-build-env build; then
+    		runqemu qemux86-64 core-image-patchtest \
+    			nographic kvm \
+    			qemuparams="-snapshot \
+    	                            -fsdev local,id=test_dev,path=$SHAREDIR,security_model=mapped \
+    	                            -device virtio-9p-pci,fsdev=test_dev,mount_tag=test_mount"
+    	else
+    		echo 'oe-init-build-env could not be sourced'
+        fi
     else
-	echo 'oe-init-build-env could not be sourced'
+	echo "Please run create-guest-machine -g $GUESTDIR"
+	exit 1
     fi
 )
 
